### ISSUE TITLE
Source for fungi dataset missing

### ISSUE THREAD

**Issue by lajello** [anderzzz/monkey_caput#1]
Great project! I was trying to reproduce the steps from your excellent tutorial, but noticed that the class for loading the fungi dataset is missing (e.g., `from fungiimg import UnNormalizeTransform`). Would it be possible to share the relevant code and data?

**Comment by anderzzz** [comment]
Thanks for the kind remarks. Appreciated.

On the specific line you reference, like [this one](https://github.com/anderzzz/monkey_caput/blob/d4789446636953377d1c709207ce15421897eeb9/ae_runs.py#L8), that is a mistake by me. The correct place to import that transform from can be seen in `la_runs`, see [this line](https://github.com/anderzzz/monkey_caput/blob/d4789446636953377d1c709207ce15421897eeb9/la_runs.py#L13). I will fix this issue. Thanks for pointing it out.

Specifically about the image raw data, the story is I scraped the images from the [public database](https://svampe.databasen.org) (non-trivial effort). But since I am not the copyright owner, I have not published the scraped dataset. I have not been able to get a clear response from the database owners (and the images themselves are collected by mostly Danish hobby mycologists), so for now the specific images sit on my hard drive. You can see for example how the paths to said files on my drive are referenced [on this line](https://github.com/anderzzz/monkey_caput/blob/d4789446636953377d1c709207ce15421897eeb9/la_runs.py#L21).

It is interesting to note that a subset of these images were part of an old Kaggle competition. However, I was not able to get hold of that data, which anyways was not quite what I wanted. You can see some comments I made on that to the database owners in [this Github issue](https://github.com/visipedia/fgvcx_fungi_comp/issues/2). Maybe you are able to make more progress from there?

In short, you are currently not able to reproduce my work from start to finish. The code was written to be modular, however, so if you have your own image dataset, then the only change required in the training and evaluation code is [this line](https://github.com/anderzzz/monkey_caput/blob/d4789446636953377d1c709207ce15421897eeb9/_learner.py#L104). On that line you would put your own function that returns a [PyTorch Dataset](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html). In other words, some variant of [fungidata.py](https://github.com/anderzzz/monkey_caput/blob/master/fungidata.py) would be yours to write. 

I know reproducibility is highly desirable, and it would have been satisfying to upload the dataset to a dataset server. As a non-academic I have additional limits to navigate, however, and the compromise above was what I went for.

**Comment by lajello** [comment]
Thanks for the fast response! I totally understand, and you've already done a lot by providing all the code. I will write a class to load a different dataset then. Marking this as closed. Cheers!

**Comment by lajello** [comment]
Thanks for the fast response! I totally understand, and you've already done a lot by providing all the code. I will write a class to load a different dataset then. Marking this as closed. Cheers!
